dataSource:
  driverClassName: com.mysql.jdbc.Driver
  dbCreate: create-drop
  username: root
  password: ''

environments:
  development:
    dataSource:
      dbCreate: create-drop
      url: "jdbc:mysql://localhost:3306/user?useUnicode=yes&characterEncoding=UTF-8&useJDBCCompliantTimezoneShift=true&useLegacyDatetimeCode=false&serverTimezone=UTC"